### ISSUE TITLE
Release on Rubygems.org

### ISSUE THREAD

**Issue by mindreframer** [tomdalling/rschema#2]
Hey Tom, 

I took the liberty to release this gem under my account: 
https://rubygems.org/gems/rschema

To make you owner of it, I would need the email address of your rubygems-account. 

```
    $ gem owner rschema -a tom@tomdalling.com
    Adding tom@tomdalling.com: Owner could not be found.
```

**Comment by tomdalling** [comment]
Hi Roman,

Thanks for that. I didn't actually have a RubyGems account until a few minutes ago. The address `tom@tomdalling.com` should work now.

**Comment by mindreframer** [comment]
works now! 

    $ gem owner rschema -a tom@tomdalling.com
    Owner added successfully.
    Owners for gem: rschema
      - tom@tomdalling.com
      - roman.heinrich@gmail.com

Check rake -T for releasing tasks. And thanks for the nice gem!
