### ISSUE TITLE
Some kind of built-in schema for boolean

### ISSUE THREAD

**Issue by mordocai** [tomdalling/rschema#4]
This may exist somewhere and I missed it, but there should be a way to check whether a given value is boolean in the schema.

My current workaround is:

    predicate { |n| n.is_a?(TrueClass) || n.is_a?(FalseClass)}

If you could give a bit of direction on how this should work I am willing to submit a pull request.

**Comment by tomdalling** [comment]
This actually didn't exist until just now. I've implemented `BooleanSchema` as an object so that it can play nicely with coercion, down the road.
