### ISSUE TITLE
Validation errors should include what class the invalid object is

### ISSUE THREAD

**Issue by mordocai** [tomdalling/rschema#5]
In regards to errors like this:

    RSchema::ValidationError:
       {"list"=>{0=>{"thing"=>"is not a Float"}}}

This should say something like:

    RSchema::ValidationError:
         {"list"=>{0=>{"thing"=>"is not a Float, is a Integer"}}}

I'll work on a pull request for this when I get the time.

**Comment by tomdalling** [comment]
Sounds reasonable. I was already in the code, so I implemented it just now.

**Comment by mordocai** [comment]
Awesome, thanks for the quick responses!

**Comment by tomdalling** [comment]
No worries!
